debug: true
domain: amenu.ru
imgdir: images
listen: "0.0.0.0:3050"
# uploadkey: "verysecretkey"
readable:
    .jpeg: false
    .jpg: true
    .png: true
    .webp: true
secret: shouldbeverysecretstring
sizes:
    a:
    - 10
    - 10
    b:
    - 70
    - 70
    bv:
    - 52
    - 70
    o:
    - 0
    - 0
    c:
    - 200
    - 200
    cv:
    - 150
    - 200
    d:
    - 480
    - 480
    dv:
    - 480
    - 640
    e:
    - 960
    - 480
uploadable:
    .jpeg: true
    .jpg: true
    .png: true
