debug: true
domain: media.metring.com
imgdir: images
listen: "localhost:8080"
readable: 
    .jpeg: false
    .jpg: true
    .png: true
    .webp: true
# secret: shouldbeverysecretstring
sizes: 
    d:
    - 16
    - 10
    lg:
    - 1280
    - 720
    md:
    - 768
    - 432
    o:
    - 0
    - 0
    sm:
    - 384
    - 216
    xl:
    - 1920
    - 1080
    xs:
    - 64
    - 36
uploadable: 
    .jpeg: true
    .jpg: true
    .png: true